accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns = [
    #path('signup/',views.signup_view,name='signup'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'), 
]

articles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list,name='list'),
    path('create/',views.article_create,name='create'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail,name='detail'),
]

djangoblog/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('articles/',include('articles.urls')),
    path('about/',views.about),
    path('',article_views.article_list,name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager as DefaultUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _

class UserManager(DefaultUserManager):
    def managers(self):
        return self.filter(is_manager=True)

class User(AbstractUser):
    # Add any custom user fields here
    picture = models.ImageField(upload_to='media/', default='default.png', null=True)
    is_manager = models.BooleanField(default=False)
    is_coordinator = models.BooleanField(default=False)

    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    # Add related_name attributes to avoid clashes
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name=_('groups'),
        blank=True,
        related_name='custom_user_set'  # Add a related_name here
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name=_('user permissions'),
        blank=True,
        related_name='custom_user_set'  # Add a related_name here
    )

    def __str__(self):
        return self.username

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from .models import User  

class UserRegistrationForm(UserCreationForm):
    picture = forms.ImageField(required=False)
    is_manager = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    )
    is_coordinator = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    )

    class Meta:
        model = User  
        fields = ['username', 'password1', 'password2', 'picture', 'is_manager', 'is_coordinator']
        labels = {
            'username': _('Username'),
            'password1': _('Password'),
            'password2': _('Confirm Password'),
            'picture': _('Profile Picture'),
            'is_manager': _('Manager'),
            'is_coordinator': _('Coordinator'),
        }

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb',]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserRegistrationForm
from django.contrib.auth import login, logout

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)  
            return redirect('articles:list')  
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def user_profile(request):
    user = request.user
    print("is_manager:", user.is_manager)
    print("is_coordinator:", user.is_coordinator)

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('articles:list')
    
def profile(request):
    return render(request, 'accounts/profile.html', {'user': request.user})
    

articles/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date');
    return render(request, 'articles/article_list.html', { 'articles': articles })

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', { 'article': article })

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'form': form })

djangoblog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request,'homepage.html')    
    #return HttpResponse('homepage')

def about(request):
    return render(request,'about.html')
    #return HttpResponse('about')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:register' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base_layout.html' %}
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
{% block content %}
    
  <h2><u>User Profile</u></h2>
  <p><strong>Username:</strong> {{ user.username }}</p>
  <p><strong>Profile Picture:</strong></p>
  <img src="{{ user.picture.url }}" alt="{{ user.username }}" class="img-thumbnail"/>
  <p><strong>Roles:</strong></p>
  <ul>
    {% if user.is_manager %}<li>Manager</li>{% endif %}
    {% if user.is_coordinator %}<li>Coordinator</li>{% endif %}
  </ul>
  <center><a href="{% url 'articles:list' %}"><u>Back to Home</u></a></center>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Register</h1>
    <form class="site-form" action="{% url 'accounts:register' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Articles List</h1>
    <div class="articles">
    {% for article in articles %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>{{ article.snippet }}</p>
            <p>{{ article.date }}</p>
            <p class="author">added by {{ article.author.username }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>Know More about the blog</h1>
    
</body>
</html>

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:register' %}">Register</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the Homepage</h1>
    <p> Welcome to the blog</p>
    
</body>
</html>